### PR TITLE
Add command mode support

### PR DESCRIPTION
**Pull request by lsun100**
This pull request has the two commits:

Add support for command mode
Fix some coding style issue

### CODE REVIEW

**Review by DLNvda — DISMISSED** [review]
LGTM

**Review by DLNvda — COMMENTED** [review]
LGTM

**Comment by pgeng-nv** [comment]
Do we want to update the man page for the new command mode?

**Comment by lsun100** [comment]
> Do we want to update the man page for the new command mode?

Good point. I'll update it.

**Pull request merged**
